### ISSUE TITLE
Installing sdist from setuptools-download rework requires `wheel`

### ISSUE THREAD

**Issue by scop** [shellcheck-py/shellcheck-py#112]
An issue I ran into when working on a project pretty much copy-pasted from here:

As of f733319f11dead54dd555217c66dc983c0ba1cc9, installing the generated sdist requires `wheel` installed to work. It isn't e.g. in standard venvs created by `python3 -m venv` (or ones pre-commit creates, don't remember offhand if they're the same).

Adding `wheel` to the dependencies does not work as deps get installed too late to help with this. Haven't tested if having `wheel` in pre-commit's `additional_dependencies` would help, but I suspect not. Anyway that would be a pre-commit specific fix only.

I wonder if something could be sanely done about this? Sample build log attached.

[out.txt](https://github.com/shellcheck-py/shellcheck-py/files/13324840/out.txt)

**Comment by asottile** [comment]
your version of pip is too old

**Comment by asottile** [comment]
actually it's just that your version of setuptools is too old

**Comment by asottile** [comment]
which for pre-commit would mean your version of virtualenv or pre-commit is too old

**Comment by scop** [comment]
No pre-commit involved here, but it appears a recent enough python with venv or separate virtualenv is needed indeed, upgrading pip or setuptools does not seem to make a difference. Good to know, but that's somewhat unfortunate as just like wheel, it's not something that can be automatically pulled in.
