### ISSUE TITLE
Make `pipx install shellcheck` work

### ISSUE THREAD

**Issue by zed** [shellcheck-py/shellcheck-py#125]
`-py` suffix is redundant (the package is on PyPI--*Python* Package Index) or misleading because it might imply re-implementation in Python of the `shellcheck` utility.

`pipx install shellcheck` is straightforward. You run it, you get `shellcheck` command in your path (not `shellcheck-py`).

**Comment by asottile** [comment]
we're not changing the package name, sorry

**Comment by zed** [comment]
Could you consider creating an alias (so that installing `shellcheck` would install `shellcheck-py` package if you prefer that name) Here's a helper to make one package name to install another: https://github.com/simonw/pypi-rename

It would be a shame if `pipx install shellcheck` installed something unrelated.

**Comment by asottile** [comment]
please take no for an answer
