### ISSUE TITLE
RISC-V Support？

### ISSUE THREAD

**Issue by JocelynPanPan** [shellcheck-py/shellcheck-py#129]
ValueError: `shellcheck-binary` is not supported on your platform

(debug info):
- os_name='posix'
- sys_platform='linux'
- platform_machine='riscv64'

I encountered the above problems when installing on the RISC-V architecture. Is there any solution?

**Comment by bibz** [comment]
It looks like `shellcheck` is indeed [released](https://github.com/koalaman/shellcheck/releases) for RISC-V. I've created a PR to include it here as well.
