### ISSUE TITLE
Pre-commit fails on apple M2 chip

### ISSUE THREAD

**Issue by christian-steinmeyer** [shellcheck-py/shellcheck-py#85]
Running the pre-commit hook on my M2 yields 

```
[Errno 86] Bad CPU type in executable: '<USER_HOME>/.cache/pre-commit/repojey4b_h7/py_env-python3.11/bin/shellcheck'
```

with pre-commit installed via brew and 

- pre-commit 3.0.2
- Homebrew 3.6.20

**Comment by asottile** [comment]
this simply wraps the shellcheck binary -- nothing we can do
