### ISSUE TITLE
Uses deprecated Setuptools license_file

### ISSUE THREAD

**Issue by henryiii** [shellcheck-py/shellcheck-py#99]
With the latest version of Setuptools, I'm getting:

```
                  ********************************************************************************
                  The license_file parameter is deprecated, use license_files instead.
          
                  By 2023-Oct-30, you need to update your project and remove deprecated calls
                  or your builds will no longer be supported.
          
                  See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                  ********************************************************************************
```

By the way, have you looked into providing wheels for the package, probably using cibuildwheel? Ideally, an end user shouldn't be running setup.py at all if possible. :)

Also, I'd highly recommend adding a `pyproject.toml`, all packages should have one (ideally before 3.12 comes out, as it removed distutils and setuptools is no longer pre-installed everywhere).

**Comment by asottile** [comment]
it doesn't

**Comment by henryiii** [comment]
Ahh, I see this was fixed already in https://github.com/shellcheck-py/shellcheck-py/commit/d36de88ab407394919f9e8dfbaec50fa16a63f5a - Thanks!
